import = ["~/dotfiles/.config/alacritty/themes/kanagawa_wave.toml"]

[cursor]
style = "Beam"


[font]
size = 14

[font.bold]
family = "Iosevka Term"
style = "Bold"


[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Amir Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[shell]
args = ["new-session", "-A", "-D", "-s", "general"]
program = "/usr/bin/tmux"

[window]
decorations = "none"
opacity = 0.9

[env]
TERM = "xterm-256color"
